services:
  - type: web
    name: movie-recommendation-api
    env: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn movie_recommendation_project.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: movie-recommendation-db
          property: connectionString
      - key: ALLOWED_HOSTS
        value: "*"

databases:
  - name: movie-recommendation-db
    plan: free