# Generated by Django 4.2.11 on 2025-09-20 14:58

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('watched_at', models.DateTimeField(auto_now_add=True)),
                ('watch_duration', models.PositiveIntegerField(blank=True, help_text='Duration watched in minutes', null=True)),
                ('completed', models.BooleanField(default=False, help_text='Whether the movie was watched completely')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watched_by', to='movies.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'watch_history',
                'ordering': ['-watched_at'],
                'indexes': [models.Index(fields=['user', 'watched_at'], name='watch_histo_user_id_1964c9_idx'), models.Index(fields=['movie'], name='watch_histo_movie_i_7e7df5_idx'), models.Index(fields=['watched_at'], name='watch_histo_watched_3c85b2_idx')],
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.DecimalField(decimal_places=1, help_text='Rating score (0.5-5.0 stars)', max_digits=2, validators=[django.core.validators.MinValueValidator(0.5), django.core.validators.MaxValueValidator(5.0)])),
                ('review', models.TextField(blank=True, help_text='Optional review text')),
                ('rated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='movies.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ratings',
                'ordering': ['-rated_at'],
                'indexes': [models.Index(fields=['user', 'movie'], name='ratings_user_id_a083ff_idx'), models.Index(fields=['movie', 'score'], name='ratings_movie_i_699a36_idx'), models.Index(fields=['rated_at'], name='ratings_rated_a_52afbe_idx')],
                'unique_together': {('user', 'movie')},
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('favorited_at', models.DateTimeField(auto_now_add=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='movies.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'favorites',
                'ordering': ['-favorited_at'],
                'indexes': [models.Index(fields=['user', 'favorited_at'], name='favorites_user_id_adf9ae_idx'), models.Index(fields=['movie'], name='favorites_movie_i_dcb6ec_idx')],
                'unique_together': {('user', 'movie')},
            },
        ),
    ]
