# Generated by Django 4.2.11 on 2025-09-20 14:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendationEngine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('algorithm_type', models.CharField(choices=[('popularity', 'Popularity Based'), ('genre', 'Genre Based'), ('collaborative', 'Collaborative Filtering'), ('content', 'Content Based'), ('hybrid', 'Hybrid Approach')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'recommendation_engines',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserRecommendation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.DecimalField(decimal_places=4, help_text='Recommendation confidence score (0.0-1.0)', max_digits=5)),
                ('reason', models.TextField(blank=True, help_text='Explanation for the recommendation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clicked', models.BooleanField(default=False)),
                ('clicked_at', models.DateTimeField(blank=True, null=True)),
                ('engine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='recommendations.recommendationengine')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommended_to', to='movies.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_recommendations',
                'ordering': ['-score', '-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='user_recomm_user_id_c21cce_idx'), models.Index(fields=['movie'], name='user_recomm_movie_i_ad213c_idx'), models.Index(fields=['score'], name='user_recomm_score_2c51aa_idx')],
                'unique_together': {('user', 'movie', 'engine')},
            },
        ),
        migrations.CreateModel(
            name='TrendingMovie',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=10)),
                ('rank', models.PositiveIntegerField()),
                ('score', models.DecimalField(decimal_places=2, help_text='Trending score based on views, ratings, etc.', max_digits=10)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trending_periods', to='movies.movie')),
            ],
            options={
                'db_table': 'trending_movies',
                'ordering': ['period', 'rank'],
                'indexes': [models.Index(fields=['period', 'date', 'rank'], name='trending_mo_period_7a8944_idx'), models.Index(fields=['movie', 'period'], name='trending_mo_movie_i_9cb345_idx')],
                'unique_together': {('movie', 'period', 'date')},
            },
        ),
    ]
